### ISSUE TITLE
TwitterKit overwrites defined URL schemes on iOS

### ISSUE THREAD

**Issue by noughts** [twitter/twitter-kit-unity#1]
Hi,
I found a bug that TwitterKit removes URL schemes added by other post process.

It seems that the predefined CFBundleURLTypes is overwritten and disappears because there is CreateArray() with the following code.
https://github.com/twitter/twitter-kit-unity/blob/master/source/Assets/Twitter/Editor/TwitterPostProcess.cs#L51

I think it would be better to add the presence confirmation process as follows.
```csharp
PlistElementArray bundleURLTypesArray = rootDict["CFBundleURLTypes"] as PlistElementArray;
if( bundleURLTypesArray == null ){
    bundleURLTypesArray = rootDict.CreateArray ("CFBundleURLTypes");
}
```

Environment:
Unity 5.6.2
Xcode 8.3.3

Sorry for my poor English.
Thanks.

**Comment by adamc01** [comment]
Hi Koichi,
Thank you for reporting this bug! We have fixed the issue in [v3.1.1](https://github.com/twitter/twitter-kit-unity/releases/tag/v3.1.1).

regards,
Adam
