### ISSUE TITLE
Demo won't open in Unity 5.3.3f1

### ISSUE THREAD

**Issue by denggoon** [twitter/twitter-kit-unity#14]
This form is for reporting issues in the Twitter Kit for Unity library. For all other developer questions/issues about Twitter please visit [Twitter Community](https://twittercommunity.com/).

**Bug Report**

We work constantly to fix bugs, tweak functionality and improve device support. Providing detailed feedback will help us to quickly resolve your issue.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
1. Install Unity 5.3.3f1
2. Download Latest TwitterKit from AssetStore and import it into project
3. Try opening TwitterDemo.unity (scene)

* Expected behavior:
1. Error Message appears:
Failed to load 'Assets/Twitter/Demo/Scene/TwitterDemo.unity' because its serialized file version is higher than what this version of Unity supports.
2. Demo Scene won't open

* SDK Version: 3.2.1
* Unity Version: 5.3.3f1
* Device name and OS version:
Windows 10

**Feature Request**

We are seeking fix contributions over external feature PRs. If you have anything you'd like to contribute, we recommend discussing it with the core team before writing it.

* Describe the feature in as much detail as possible:
* Include sample usage where appropriate:

**Comment by adamc01** [comment]
Please try Unity 2017.1 or later
