### ISSUE TITLE
Not posting on Android, without image on iOS

### ISSUE THREAD

**Issue by ghost** [twitter/twitter-kit-unity#15]
Hi! Nothing happens after pressing "Tweet" button on Android, and posting without image on iOS. But we can see image preview before tweet.

* SDK Version: 3.2.1
* Unity 2017.2.0p2
* iPhone 6s iOS 11.1.2, Meizu M3s Android 5.1, Fly iq446 Android 4.1.2

**Comment by ghost** [comment]
upd: if post with imageUri as web-link

**Comment by adamc01** [comment]
The Composer currently does not support passing in an image URL as the URI (even though it shows up in the preview). You need to pass a local URI.
