### ISSUE TITLE
On iOS 10.3.3, the user does not return to the application from safari after login.

### ISSUE THREAD

**Issue by Arzrein** [twitter/twitter-kit-unity#17]
**Bug Report**

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
Login request when the Twitter app is uninstalled

* Expected behavior:
The user does not return to the application from Safari after login.

* SDK Version: 
3.2.1
* Unity Version: 
5.6.4f1
* Device name and OS version: 
iPhone 5, iOS 10.3.3

**Comment by adamc01** [comment]
Try upgrading to Unity 2017+

**Comment by Arzrein** [comment]
Does not work with Unity 5.6.4f1?
