### ISSUE TITLE
twitter login error on devcies without twitter app

### ISSUE THREAD

**Issue by Jason-Zy** [twitter/twitter-kit-unity#18]
i am using this twitter sdk version 3.1.1 in my unity game , it always error when i try to init and login on devices without twitter app,  when i try it on devices with twitter app ,some of them are ok, but some of them cause my game crash? can you help me? here is the error code bellow:

E/Twitter (12790): Invalid json: <?xml version="1.0" encoding="UTF-8"?>

E/Twitter (12790): <hash>

E/Twitter (12790):   <error>Desktop applications only support the oauth_callback value 'oob'</error>

E/Twitter (12790):   <request>/oauth/request_token</request>

E/Twitter (12790): </hash>

E/Twitter (12790): 

E/Twitter (12790): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

E/Twitter (12790): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)

E/Twitter (12790): 	at com.twitter.sdk.android.core.models.SafeListAdapter$1.read(SafeListAdapter.java:45)

E/Twitter (12790): 	at com.twitter.sdk.android.core.models.SafeMapAdapter$1.read(SafeMapAdapter.java:45)

E/Twitter (12790): 	at com.google.gson.Gson.fromJson(Gson.java:887)

E/Twitter (12790): 	at com.google.gson.Gson.fromJson(Gson.java:852)

E/Twitter (12790): 	at com.google.gson.Gson.fromJson(Gson.java:801)

E/Twitter (12790): 	at com.google.gson.Gson.fromJson(Gson.java:773)

E/Twitter (12790): 	at com.twitter.sdk.android.core.TwitterApiException.parseApiError(TwitterApiException.java:110)

E/Twitter (12790): 	at com.twitter.sdk.android.core.TwitterApiException.readApiError(TwitterApiException.java:95)

E/Twitter (12790): 	at com.twitter.sdk.android.core.TwitterApiException.<init>(TwitterApiException.java:43)

E/Twitter (12790): 	at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)

E/Twitter (12790): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)

E/Twitter (12790): 	at android.os.Handler.handleCallback(Handler.java:808)

E/Twitter (12790): 	at android.os.Handler.dispatchMessage(Handler.java:103)

E/Twitter (12790): 	at android.os.Looper.loop(Looper.java:193)

E/Twitter (12790): 	at android.app.ActivityThread.main(ActivityThread.java:5386)

E/Twitter (12790): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/Twitter (12790): 	at java.lang.reflect.Method.invoke(Method.java:515)

E/Twitter (12790): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)

E/Twitter (12790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)

E/Twitter (12790): 	at dalvik.system.NativeStart.main(Native Method)

E/Twitter (12790): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

E/Twitter (12790): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)

E/Twitter (12790): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)

E/Twitter (12790): 	... 20 more

E/Twitter (12790): Failed to get request token

E/Twitter (12790): com.twitter.sdk.android.core.TwitterApiException: HTTP request failed, Status: 401

E/Twitter (12790): 	at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)

E/Twitter (12790): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)

E/Twitter (12790): 	at android.os.Handler.handleCallback(Handler.java:808)

E/Twitter (12790): 	at android.os.Handler.dispatchMessage(Handler.java:103)

E/Twitter (12790): 	at android.os.Looper.loop(Looper.java:193)

E/Twitter (12790): 	at android.app.ActivityThread.main(ActivityThread.java:5386)

E/Twitter (12790): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/Twitter (12790): 	at java.lang.reflect.Method.invoke(Method.java:515)

E/Twitter (12790): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)

E/Twitter (12790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)

E/Twitter (12790): 	at dalvik.system.NativeStart.main(Native Method)

E/Twitter (12790): Authorization completed with an error

E/Twitter (12790): com.twitter.sdk.android.core.TwitterAuthException: Failed to get request token

E/Twitter (12790): 	at com.twitter.sdk.android.core.identity.OAuthController$1.failure(OAuthController.java:94)

E/Twitter (12790): 	at com.twitter.sdk.android.core.internal.oauth.OAuth1aService$1.failure(OAuth1aService.java:191)

E/Twitter (12790): 	at com.twitter.sdk.android.core.Callback.onResponse(Callback.java:42)

E/Twitter (12790): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)

E/Twitter (12790): 	at android.os.Handler.handleCallback(Handler.java:808)

E/Twitter (12790): 	at android.os.Handler.dispatchMessage(Handler.java:103)

E/Twitter (12790): 	at android.os.Looper.loop(Looper.java:193)

E/Twitter (12790): 	at android.app.ActivityThread.main(ActivityThread.java:5386)

E/Twitter (12790): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/Twitter (12790): 	at java.lang.reflect.Method.invoke(Method.java:515)

E/Twitter (12790): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)

E/Twitter (12790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)

E/Twitter (12790): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by LukeFireproof** [comment]
I'm having a similar problem with this. On a device without twitter installed, I get a login failure error with no twitter window popping up:

_Twitter login failed: code=0 msg=Failed to get request token_

Callback url is set as recommended in similar solutions to this issue.

And with twitter installed I get a Tweet Failed when calling Twitter.Compose() with no reason given. The actual login process seems to work.  Same code works fine in iOS build.

**Comment by LukeFireproof** [comment]
I managed to fix the Tweet Failed bug on Android by specifying a screenshot to upload (I used a local screenshot). On iOS the same code ran fine with an empty string for the image path, which is slightly baffling.

**Comment by AndroidDeveloperLB** [comment]
Wait, how did you fix the login issue, when Twitter app isn't installed?

**Comment by Jason-Zy** [comment]
to solve this issue，just fill a callback URL on the Twitter developer console

**Comment by AndroidDeveloperLB** [comment]
@Jason-Zy I think I got it. I added this exact thing into the [twitter console](https://apps.twitter.com/app/), inside settings-> Callback URLs :

> twittersdk://

![image](https://user-images.githubusercontent.com/5357526/46063587-f1fca180-c175-11e8-84d4-f641ef451561.png)
