### ISSUE TITLE
Unable to submit to AppStore

### ISSUE THREAD

**Issue by noughts** [twitter/twitter-kit-unity#2]
Hi,

It seems that we can not submit iOS App with twitter-kit-unity to AppStore.
Following error will be displayed and fail.

> ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/twitterKit.app/TwitterShareExtensionUIResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

STEPS TO REPRODUCE:
1. Create new project in Unity
2. Import twitter-kit-unity 3.1.1 and set API keys
3. Build project in Unity
4. Open exported xcode project
5. Archive
6. Open Organizer window
7. Press “Upload to App Store” button and advance the process
8. “ERROR ITMS-90535” displayed and fail to submit to App Store

WORKAROUND:
Remove “Excecutable File” key from Assets/Plugins/iOS/TwitterShareExtensionUIResources.bundle/Info.plist

In the meantime, we can successfully submit to AppStore with the above workaround, but I'm not sure if this is the correct way to fix it.
Please confirm.

ENVIRONMENT:
Unity 2017.1.0f3
Xcode 8.3.3
twitter-kit-unity 3.1.1

Thank you for being patient with my Google-Translated-English.

**Comment by efrohnhoefer** [comment]
We are aware of the issue and are working to get the problem resolved. See: https://twittercommunity.com/t/unable-to-upload-ios-build-to-itunes-connect/87866/6

**Comment by noughts** [comment]
Thank you for the information.
I am looking forward to being fixed.

**Comment by adamc01** [comment]
This has been fixed, please upgrade to [v3.2.0](https://github.com/twitter/twitter-kit-unity/releases/tag/v3.2.0).
