### ISSUE TITLE
Fresh import from Asset store. Kills editor.  Every time.

### ISSUE THREAD

**Issue by twobob** [twitter/twitter-kit-unity#20]
This form is for reporting issues in the Twitter Kit for Unity library. For all other developer questions/issues about Twitter please visit [Twitter Community](https://twittercommunity.com/).

**Bug Report**

We work constantly to fix bugs, tweak functionality and improve device support. Providing detailed feedback will help us to quickly resolve your issue.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
* Expected behavior:
Can import
* SDK Version:
Latest
* Unity Version:
2018 Beta b13
* Device name and OS version:
Windows10 64 desktop build config

fresh import from Asset store.
Kills editor.  Every time.

![image](https://user-images.githubusercontent.com/915232/38846953-03fdc610-41f7-11e8-8033-56e2bd51e49b.png)

**Comment by twobob** [comment]
reported.  Just in case it isn't you
![image](https://user-images.githubusercontent.com/915232/38847013-48488e04-41f7-11e8-990c-9c4b1f99ad1e.png)

**Comment by adamc01** [comment]
Please try a stable 2017 release.

**Comment by twobob** [comment]
What about a 5.6?  I would really prefer to use that. I will check :) 
EDIT: Seems fine in 5.6.  

Doubtless the Unity Team will pick it up then :)  Thanks for your time

UNITY ISSUE. CLOSE! :)

**Comment by twobob** [comment]
Re: (Case 1027026) The Editor crashed in FileAccessor::Read when importing Twitter Kit for Unity asset
Vxxx Lxxxs

Hey, We have been able to reproduce this bug and have sent it for resolution with our developers.
We highly appreciate your contribution. If you have further questions, feel free to contact us.
Sincerely,
Vxxx
Unity QA Team

Huh, so fast :)  GJ QA Team. They beat me by 4 days!
