### ISSUE TITLE
I can not log in. (Error Code 415)

### ISSUE THREAD

**Issue by doyongid** [twitter/twitter-kit-unity#23]
* SDK Version: Lateast Version
* Unity Version: 5.6.5.p4
* Device name and OS version: iPad 10.5 /  iOS 11.4

I can not sign in on Twitter since June 13th.

Twitter policy seems to have changed.

How do I sign in with the Unity plugin?

Will I be solved simply by entering the Callback URL on the Twitter development site? I tried various methods but it does not work.

I entered the Callback URL provided by Firebase. Do you recognize only certain Callback URLs?

I was servicing the app, and this is a fatal accident. :(

Please help me.

**Comment by alistairng** [comment]
having the same issue

**Comment by doyongid** [comment]
callback uri

ios : twitterkit-API_KEY://                     [ ex : twitterkit-DKFJkfjwoDKDKjfdjklwofw:// ]

android : twittersdk://
