### ISSUE TITLE
Save a session persistently

### ISSUE THREAD

**Issue by yosun** [twitter/twitter-kit-unity#3]
How do you save a TwitterSession to be persistent via this Unity wrapper? Currently, it seems that it has to ask for the user's permission each time the user opens the app to perform any twitter api related commands?

**Comment by efrohnhoefer** [comment]
The `TwitterSession` is already persisted by the library. You can use `Twitter.Session` to get the current session.

See: https://github.com/twitter/twitter-kit-unity/blob/master/source/Assets/Twitter/Scripts/Twitter.cs#L83
