### ISSUE TITLE
App key does not refresh unless unity editor restarts

### ISSUE THREAD

**Issue by yosun** [twitter/twitter-kit-unity#4]
This form is for reporting issues in the Twitter Kit for Unity library. For all other developer questions/issues about Twitter please visit [Twitter Community](https://twittercommunity.com/).

**Bug Report**

We work constantly to fix bugs, tweak functionality and improve device support. Providing detailed feedback will help us to quickly resolve your issue.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
0. Generate two sets of app secrets and keys, each under a different twitter account. 
1) Create App A. Enter the app secret and key for App A in TwitterKit settings in Unity Editor.
2) Build the app. The Twitter permissions ask for App A. 
3) Open App B in Unity editor. 
4) Enter the app secret and key for App B in TwitterKit settings for App B. 
5) Build the app. The Twitter permissions ask for App B. 

Current solution: restarting unity editor. 
* Expected behavior: When the app secret and keys are entered in TwitterKit settings, they should be updated immediately without requiring restarting the editor. 
* SDK Version: August 12, 2017 download from Unity asset store 
* Unity Version:5.6.1p3
* Device name and OS version:iPhone 7,iOS11

**Feature Request**

We are seeking fix contributions over external feature PRs. If you have anything you'd like to contribute, we recommend discussing it with the core team before writing it.

* Describe the feature in as much detail as possible:
* Include sample usage where appropriate:

**Comment by adamc01** [comment]
I was unable to repro on Unity Version 2017.1.0f3. Try upgrading to any Unity 2017.x version.
