### ISSUE TITLE
animated gif uploads silent fail 

### ISSUE THREAD

**Issue by yosun** [twitter/twitter-kit-unity#5]
this seems to be a silent drop 

sent a gif filepath to the plugin's image parameter.

fails even though gif is within[ these recommended constraints](https://dev.twitter.com/rest/media/uploading-media#gifrecs ):

> Resolution should be <= 1280x1080 (width x height)
> Number of frames <= 350
> Number of pixels (width * height * num_frames) <= 300 million
> Filesize <= 15Mb

**Comment by adamc01** [comment]
The Composer currently does not support video or gifs.

**Comment by yosun** [comment]
that's unacceptable. gif support has been available on the main twitter API for quite some time now. please add this to twitterkit.

**Comment by adamc01** [comment]
We are aware and it is on the roadmap.

**Comment by yosun** [comment]
When in the roadmap might gif support be ready? 

I am releasing several ARKit apps this month that feature uploading gif from Unity to twitter - including major brands such as DC Comics / WB -  https://twitter.com/Yosun/status/886673032575557632

**Comment by adamc01** [comment]
You can upload gifs and video using the Twitter Composer, but of course the user would have to have the Twitter app installed in that case. Would that solve your problem in the interim? Exposing the Twitter Composer shouldn't be too difficult.

**Comment by yosun** [comment]
Can you clarify? I'm not able to get gifs and videos to upload via twitterkit unity's compose method? Should I be using another class/method to do this?

**Comment by adamc01** [comment]
That is correct, with Twitter Kit for Unity's compose method you cannot upload a gif or video. But you can modify the open source repo and add the necessary calls to call the native Twitter composer which can do gif and video (of course the user would have to have the Twitter app installed on their device for this to work though).
https://dev.twitter.com/twitterkit/android/compose-tweets

**Comment by yosun** [comment]
Can you update where on the roadmap gif and video upload is?

**Comment by aurorakb** [comment]
@yosun we struggled with the same thing. Twitter made the change about 2 years ago and it's been on their roadmap since.. We made a [custom solution for iOS devices](https://docs.megacool.co/customize#1-4-2-twitter).

**Comment by yosun** [comment]
@aurorakb congrats on getting funded :) - just added you on linkedin! 

i like how your gif solution tries to keep everything in buffer and is super fast at saving! however, your sdk currently does not support iOS 11 - same error as for the standard social share view  https://github.com/megacool/sdk/issues/22

**Comment by yosun** [comment]
@adamc01 please re-open this issue, as it hasn’t been solved yet.

**Comment by nicolajbroby** [comment]
@yosun Did you find another way of doing this?

**Comment by yosun** [comment]
sadly, no. i really wish they would not close issues that they don't want to fix - but that really isn't resolved yet!
