### ISSUE TITLE
Unity 2017.1.0f1

### ISSUE THREAD

**Issue by StefanosGiannakis** [twitter/twitter-kit-unity#6]
Hi , i am using Twitter kit for my new game , after my successful login to twitter, app crashes. I search on web but i can't find examples .. In my opinion documentation is poor

Two things make a good documentation:
1st. Examples 
2nd. Explanations of errors

Thx , in Advance , i think a good example must have the basic functionalities of Log In , Log Out and Share ... that's all folks...
check your competitors :-)
cyah
.

**Comment by adamc01** [comment]
Have you tried running the TwitterDemo scene? It has examples of login and compose.
If you don't have request email permission enabled in your Twitter app's settings then in TwitterDemo.cs, in the startLogin() method replace `LoginCompleteWithEmail` with `LoginCompleteWithCompose`
