### ISSUE TITLE
Login does not work on iOS

### ISSUE THREAD

**Issue by gaborvass** [twitter/twitter-kit-unity#7]
Hi,

When Twitter web page tries open Unity app again after successful authentication, app crashes.
The problem can be resolved by implementing `- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options` method. 
Also `twitter` and `twitterauth` values are not added to `LSApplicationQueriesSchemes` in Info.plist file.

**Comment by adamc01** [comment]
Thanks for pointing out the openURL issue, it will be fixed in the next release.
As for the values not being added to LSApplicationQueriesSchemes in the plist file, have you tried running the TwitterDemo scene? The post processor should be adding them automatically.
